---
- name: create data and log dirs
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ hadoop_data_dir }}"
    - "{{ hadoop_log_dir }}"

- name: set JAVA_HOME
  become: yes
  lineinfile:
    path: "{{ hadoop_home }}/etc/hadoop/{{ item }}-env.sh"
    regexp: 'export JAVA_HOME=.*'
    line: 'export JAVA_HOME="{{ java_home }}"'
    backrefs: yes
  with_items:
    - hadoop
    - mapred
    - yarn

- name: set HADOOP_LOG_DIR
  become: yes
  lineinfile:
    path: "{{ hadoop_home }}/etc/hadoop/hadoop-env.sh"
    regexp: 'export HADOOP_LOG_DIR=.*'
    line: 'export HADOOP_LOG_DIR="{{ hadoop_log_dir }}"'
    backrefs: yes

- name: configure site files
  become: yes
  template:
    src: "{{ item }}-site.xml.j2"
    dest: "{{ hadoop_home }}/etc/hadoop/{{ item }}-site.xml"
    mode: 0644
  with_items:
    - core
    - hdfs
    - mapred
    - yarn

- name: format hdfs
  command: "{{ hadoop_home }}/bin/hadoop namenode -format"
  args:
    creates: "{{ hdfs_name_dir }}"
