---
- name: install hadoop
  become: yes
  unarchive:
    src: "http://www-eu.apache.org/dist/hadoop/common/hadoop-{{ hadoop_version }}/hadoop-{{ hadoop_version }}.tar.gz"
    dest: "{{ hadoop_parent }}"
    remote_src: yes
    creates: "{{ hadoop_home }}"

- name: symlink hadoop home
  become: yes
  file:
    state: link
    src: "{{ hadoop_home }}"
    dest: "{{ hadoop_parent }}/hadoop"

- name: add hadoop commands to the path
  become: yes
  template:
    src: hadoop.sh.j2
    dest: /etc/profile.d/hadoop.sh
    mode: 0644
